### PR TITLE
Kick in waiting

### PR DESCRIPTION
**Pull request by tylerbordeaux**
You can now kick players in the waiting for questionnaire player progress screen. If waiting players are kicked, the game will automatically start. You can only kick if there are more than two players.

### CODE REVIEW

**Review by AyushiMukherjee — COMMENTED** [review]
this branch has merge conflicts

**Comment by tylerbordeaux** [comment]
No more conflicts

**Review by Arrowship06 — CHANGES_REQUESTED** [review]
Separate kicking players in the lobby from kicking in the questionnaire

**Review by Arrowship06 — APPROVED** [review]
Awesome!

**Pull request merged**
