### PR TITLE
End-of-Week Merge for Final Presentation

### PR DESCRIPTION
**Pull request by josephmaxwellhyland**

### CODE REVIEW

**Comment by josephmaxwellhyland** [comment]
Going to try to do this at the end of the day on 8/4

**Review by Arrowship06 — APPROVED** [review]
looks good to me

**Review by AyushiMukherjee — APPROVED** [review]
looks good

**Review by matandon — APPROVED** [review]
hopefully looks good?

**Review by tylerbordeaux — APPROVED** [review]
Zero bugs!

**Pull request merged**
