### PR TITLE
Player UI fill screen

### PR DESCRIPTION
**Pull request by tylerbordeaux**
Display always fits screen now so you cannot scroll.

### CODE REVIEW

**Comment by josephmaxwellhyland** [comment]
Can we remove the whitespace surrounding the content?

image

**Comment by tylerbordeaux** [comment]
Screenshot 2023-07-18 at 9 26 06 AM

**Comment by josephmaxwellhyland** [comment]
Just realized we do still want it to scroll for the questionnaire page - not sure how many questions there will be or what screen size the mobile devices will have

image

**Comment by matandon** [comment]
Also addressed issue #190

**Review by matandon — APPROVED** [review]
looks good!

**Review by alyssa11235 — CHANGES_REQUESTED** [review]
Scroll thing

**Review by alyssa11235 — APPROVED** [review]
Looks good

**Pull request merged**
